# if (!require(pacman)) install.packages('pacman')
# if (!require(particlesjs)) devtools::install_github("dreamRs/particlesjs")

library(shiny)
library(waiter)
library(tippy)
library(easyPubMed) 
library(tidyverse)
library(tidytext)
library(tm)
library(ggiraph)
library(wordcloud)
library(particlesjs)

source('functions.R')
api_key <- read_lines('assets/ncbi-key.txt')